# Configuration file of Harbor Acceleration Service

# http related config
server:
  name: API
  # listened host for http
  host: 0.0.0.0
  # port for http
  port: 2077

metric:
  # export metrics on `/metrics` endpoint
  enabled: true

provider:
  source:
    # hostname of harbor service
    hub.harbor.com:
      # base64 encoded `<robot-name>:<robot-secret>` for robot
      # account created in harbor
      auth: YTpiCg==
      # skip verifying server certs for HTTPS source registry
      insecure: false
      webhook:
        # webhook request auth header configured in harbor
        auth_header: header
    localhost:
      auth: YWRtaW46SGFyYm9yMTIzNDU=
  # work directory of acceld
  work_dir: /tmp
  gcpolicy:
      # size threshold that triggers GC, the oldest used blobs will be reclaimed if exceeds the size.
      threshold: 1000MB
  # remote cache record capacity of converted layers, default is 200.
  cache_size: 200

converter:
  # number of worker for executing conversion task
  worker: 5
  # enable to add harbor specified annotations to converted image for tracking.
  harbor_annotation: true
  # only convert images for specific platforms, leave empty for all platforms.
  # platforms: linux/amd64,linux/arm64
  driver:
    # accelerator driver type: `nydus`
    type: nydus
    config:
      work_dir: /tmp

      # `nydus-image` binary path, download it from:
      # https://github.com/dragonflyoss/image-service/releases (require v2.0.0 or higher)
      # builder: nydus-image

      # convert to OCI-referenced nydus zran image.
      oci_ref: true

      # with this option, we can track all nydus images associated with
      # an OCI image. For example, in Harbor we can cascade to show nydus
      # images linked to an OCI image, deleting the OCI image can also delete
      # the corresponding nydus images. At runtime, nydus snapshotter can also
      # automatically upgrade an OCI image run to nydus image.
      with_referrer: true
  rules:
    # add suffix to tag of source image reference as target image reference
    - tag_suffix: -nydus-oci-ref
    # add suffix to tag of source image reference as remote cache reference, leave empty to disable remote cache.
    - cache_tag_suffix: -nydus-cache
