name: Concurrent Test

on:
  push:
    branches: [ '*' ]
    paths-ignore: [ '**.md']
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**.md']

jobs:
  concurrent_test_same:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Golang
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build Accel
      run: |
        make

    - name: Install Harbor
      run: |
        HARBOR_VERION=$(curl https://api.github.com/repos/goharbor/harbor/releases/latest | jq -r '.tag_name')
        wget https://github.com/goharbor/harbor/releases/download/${HARBOR_VERION}/harbor-offline-installer-${HARBOR_VERION}.tgz
        tar xzvf harbor-offline-installer-${HARBOR_VERION}.tgz
        cp ./script/integration/harbor.yml harbor/harbor.yml
        cd harbor
        sudo ./install.sh

    - name: Prepare Test Image
      run: |
        sudo docker pull wordpress
        sudo docker login -u admin -p Harbor12345 localhost
        sudo docker tag wordpress localhost/library/wordpress
        sudo docker push localhost/library/wordpress

    - name: Concurrent Test
      run: |
        NYDUS_VERSION=$(curl https://api.github.com/repos/Dragonflyoss/nydus/releases/latest | jq -r '.tag_name')
        wget https://github.com/dragonflyoss/image-service/releases/download/${NYDUS_VERSION}/nydus-static-${NYDUS_VERSION}-linux-amd64.tgz
        sudo tar xzvf nydus-static-${NYDUS_VERSION}-linux-amd64.tgz --wildcards --strip-components=1 -C /usr/bin/ nydus-static/*
        ./script/integration/concurrent/test-same.sh wordpress

  concurrent_test_diff:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Golang
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build Accel
      run: |
        make

    - name: Install Harbor
      run: |
        HARBOR_VERION=$(curl https://api.github.com/repos/goharbor/harbor/releases/latest | jq -r '.tag_name')
        wget https://github.com/goharbor/harbor/releases/download/${HARBOR_VERION}/harbor-offline-installer-${HARBOR_VERION}.tgz
        tar xzvf harbor-offline-installer-${HARBOR_VERION}.tgz
        cp ./script/integration/harbor.yml harbor/harbor.yml
        cd harbor
        sudo ./install.sh

    - name: Prepare Test Image
      run: |
        images=("nginx" "alpine" "busybox")
        for image in ${images[@]}; do
          sudo docker pull $image
          sudo docker tag $image localhost/library/$image
        done
        sudo docker login -u admin -p Harbor12345 localhost
        for image in ${images[@]}; do
          sudo docker push localhost/library/$image
        done

    - name: Concurrent Test
      run: |
        NYDUS_VERSION=$(curl https://api.github.com/repos/Dragonflyoss/nydus/releases/latest | jq -r '.tag_name')
        wget https://github.com/dragonflyoss/image-service/releases/download/${NYDUS_VERSION}/nydus-static-${NYDUS_VERSION}-linux-amd64.tgz
        sudo tar xzvf nydus-static-${NYDUS_VERSION}-linux-amd64.tgz --wildcards --strip-components=1 -C /usr/bin/ nydus-static/*
        ./script/integration/concurrent/test-diff.sh
