name: DCO Check

on:
  pull_request:
    branches: [ main ]

jobs:
  dco_check:
    runs-on: ubuntu-latest
    name: DCO Check
    steps:
    - name: Get PR Commits
      id: 'get-pr-commits'
      uses: tim-actions/get-pr-commits@c64db31d359214d244884dd68f971a110b29ab83
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: DCO Check
      uses: tim-actions/dco@f2279e6e62d5a7d9115b0cb8e837b777b1b02e21
      with:
        commits: ${{ steps.get-pr-commits.outputs.commits }}
