name: Unit Test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  unit_test:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.18
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Golang
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build Accel
      run: |
        go test -v -count=1 ./pkg/...
