name: Unit Test

on:
  push:
    branches: [ '*' ]
    paths-ignore: [ '**.md', '**/misc/**', '**/script/**']
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**.md', '**/misc/**', '**/script/**']

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Golang
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Build Accel
      run: |
        go test -v -count=1 ./pkg/...
