name: Webhook Test

on:
  push:
    branches: [ '*' ]
    paths-ignore: [ '**.md']
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**.md']

jobs:
  webhook_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Golang
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod

    - name: Build Accel
      run: |
        make

    - name: Install Harbor
      run: |
        HARBOR_VERION=$(curl https://api.github.com/repos/goharbor/harbor/releases/latest | jq -r '.tag_name')
        wget https://github.com/goharbor/harbor/releases/download/${HARBOR_VERION}/harbor-offline-installer-${HARBOR_VERION}.tgz
        tar xzvf harbor-offline-installer-${HARBOR_VERION}.tgz
        cp ./script/integration/harbor.yml harbor/harbor.yml
        cd harbor
        sudo ./install.sh

    - name: Webhook Test
      run: |
        # Download nydus components
        NYDUS_VERSION=$(curl https://api.github.com/repos/Dragonflyoss/nydus/releases/latest | jq -r '.tag_name')
        wget https://github.com/dragonflyoss/image-service/releases/download/${NYDUS_VERSION}/nydus-static-${NYDUS_VERSION}-linux-amd64.tgz
        sudo tar xzvf nydus-static-${NYDUS_VERSION}-linux-amd64.tgz --wildcards --strip-components=1 -C /usr/bin/ nydus-static/*
        sudo ./script/integration/webhook/test.sh
